# Generated by Django 4.2.3 on 2023-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluminum', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('arsenic', models.FloatField()),
                ('barium', models.FloatField()),
                ('cadmium', models.FloatField()),
                ('chloramine', models.FloatField()),
                ('chromium', models.FloatField()),
                ('copper', models.FloatField()),
                ('flouride', models.FloatField()),
                ('bacteria', models.FloatField()),
                ('viruses', models.FloatField()),
                ('lead', models.FloatField()),
                ('nitrates', models.FloatField()),
                ('nitrites', models.FloatField()),
                ('mercury', models.FloatField()),
                ('perchlorate', models.FloatField()),
                ('radium', models.FloatField()),
                ('selenium', models.FloatField()),
                ('silver', models.FloatField()),
                ('uranium', models.FloatField()),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
