# Generated by Django 4.2.3 on 2023-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqpred', '0002_remove_userinput_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
