# Generated by Django 4.2.3 on 2023-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqpred', '0007_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='pred',
            field=models.IntegerField(null=True),
        ),
    ]
